import os
import sqlite3
from typing import Literal, TypedDict

from langchain_community.tools import DuckDuckGoSearchRun
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import PromptTemplate
from langchain_groq import ChatGroq
from langgraph.checkpoint.sqlite import SqliteSaver
from langgraph.graph import END, StateGraph

from utils.security.F_anonymizer import anonymize_node
from utils.security.F_prompt_injection import injection_node


class GraphState(TypedDict):
	question: str
	context: str
	answer: str
	source: str
	is_safe: str


class Maternal_Agent:
	def __init__(self, searcher, model_name="llama3.2"):
		os.makedirs("messages", exist_ok=True)
		self.conn = sqlite3.connect(
			"messages/memoria_chats.db", check_same_thread=False
		)
		self.memory = SqliteSaver(self.conn)
		self.searcher = searcher
		self.llm = ChatGroq(
			model="openai/gpt-oss-20b",
			temperature=0,
			api_key=os.getenv("GROQ_API_KEY"),
		)
		self.web_search_tool = DuckDuckGoSearchRun()

		self.grader_prompt = PromptTemplate(
			template="""[ROLE]
            You are a strict and precise medical data evaluator.

            [AUDIENCE]
            Your output will be read by an automated routing system.

            [TASK]
            Assess if the retrieved medical context contains relevant and sufficient information to answer the user's question.

            [EXECUTION]
            Context: {context}
            Question: {question}

            [ACTION & FORMAT]
            Answer strictly with the exact word 'yes' if it is relevant, or the exact word 'no' if it is irrelevant or poor. Do not include any explanations, greetings, punctuation, or additional text.""",
			input_variables=["context", "question"],
		)

		self.generate_prompt = PromptTemplate(
			template="""[PERSONA]
            You are a compassionate, professional, and reliable maternal health assistant.

            [SITUATION]
            You are providing guidance and answering questions for pregnant patients based exclusively on our verified medical database.

            [ACTION]
            Answer the patient's query using ONLY the provided MEDICAL CONTEXT below.

            [CONDITIONS & CONSTRAINTS]
            - You MUST rely entirely on the MEDICAL CONTEXT provided. Do not use outside or pre-trained knowledge.
            - If the MEDICAL CONTEXT does not contain the answer, explicitly state that you cannot answer based on the available data.
            - ALWAYS recommend consulting an obstetrician if the query involves severe, painful, or unusual symptoms.

            [CRITERIA FOR SUCCESS]
            The answer directly addresses the patient's concern, is factually grounded ONLY in the context, and prioritizes maternal safety.

            [TONE]
            Empathetic, reassuring, clear, and clinically objective.

            ---
            MEDICAL CONTEXT:
            {context}

            PATIENT QUERY:
            {question}

            ANSWER:""",
			input_variables=["context", "question"],
		)

		self.app = self._build_graph()

	def retrieve_node(self, state: GraphState) -> GraphState:
		q = state["question"]
		top_k = self.searcher.search(q, top_k=3)
		contexto_recuperado = "\n\n".join(top_k["documents"][0])

		state["context"] = contexto_recuperado
		state["source"] = "local"
		return state

	def grade_node(self, state: GraphState) -> GraphState:
		chain = self.grader_prompt | self.llm | StrOutputParser()

		score = chain.invoke(
			{"context": state["context"], "question": state["question"]}
		)

		if "yes" in score.lower():
			state["source"] = "local"
		else:
			state["source"] = "web"

		return state

	def web_search_node(self, state: GraphState) -> GraphState:
		q = state["question"]
		web_results = self.web_search_tool.invoke(q)

		state["context"] = web_results
		return state

	def generate_node(self, state: GraphState) -> GraphState:
		chain = self.generate_prompt | self.llm | StrOutputParser()

		out = chain.invoke({"context": state["context"], "question": state["question"]})

		if state["source"] == "web":
			warning = """\n\n⚠️IMPORTANT NOTICE: I haven't found any information on this in my official medical database.
			This response was generated by searching the Internet to provide you with general context, so it may not be accurate or reliable.
			Please ALWAYS consult your obstetrician if you have any questions.⚠️"""
			out = out + warning

		state["answer"] = out
		return state

	def route_after_grade(self, state: GraphState) -> Literal["web_search", "generate"]:
		if state["source"] == "web":
			return "web_search"
		else:
			return "generate"

	def security_node(self, state: GraphState) -> GraphState:
		q = state["question"]
		is_safe = injection_node(self.llm, q)
		state["is_safe"] = is_safe
		if is_safe == "no":
			state["answer"] = "Security Alert: Malicious prompt detected."
		return state

	def anonymize_query_node(self, state: GraphState) -> GraphState:
		q = state["question"]
		safe_query = anonymize_node(q)
		state["question"] = safe_query
		return state

	def route_after_security(self, state: GraphState) -> str:
		if state.get("is_safe") == "no":
			return "end"
		else:
			return "anonymize"

	def _build_graph(self):
		g = StateGraph(GraphState)

		g.add_node("security", self.security_node)
		g.add_node("anonymize", self.anonymize_query_node)
		g.add_node("retrieve", self.retrieve_node)
		g.add_node("grade", self.grade_node)
		g.add_node("web_search", self.web_search_node)
		g.add_node("generate", self.generate_node)

		g.set_entry_point("security")

		g.add_conditional_edges(
			"security",
			self.route_after_security,
			{
				"end": END,
				"anonymize": "anonymize",
			},
		)

		g.add_edge("anonymize", "retrieve")
		g.add_edge("retrieve", "grade")

		g.add_conditional_edges(
			"grade",
			self.route_after_grade,
			{
				"web_search": "web_search",
				"generate": "generate",
			},
		)

		g.add_edge("web_search", "generate")
		g.add_edge("generate", END)

		return g.compile()

	def run(self, query: str, session_id: str, callbacks=None):
		inputs = {
			"question": query,
			"context": "",
			"answer": "",
			"source": "",
			"is_safe": "",
		}
		config = {
			"configurable": {"thread_id": session_id},
			"metadata": {"langfuse_session_id": session_id},
			"tags": ["paciente", "produccion"],
		}
		if callbacks:
			config["callbacks"] = callbacks
		final_state = self.app.invoke(inputs, config=config)

		return final_state["answer"]
